name: Build Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # https://crontab.cronhub.io/
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Action for checking out a repo - https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # GitHub Action to set up Docker Buildx - https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          BOT_TOKEN_TEST: ${{ secrets.BOT_TOKEN_TEST }}
          POSTGRES_HOST_TEST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT_TEST: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_NAME_TEST: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USERNAME_TEST: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD_TEST: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          cd app
          echo "SECRET_KEY=${FLASK_SECRET_KEY}" >> .env
          echo "BOT_TOKEN=${BOT_TOKEN_TEST}" >> .env
          echo "POSTGRES_HOST=${POSTGRES_HOST_TEST}" >> .env
          echo "POSTGRES_PORT=${POSTGRES_PORT_TEST}" >> .env
          echo "POSTGRES_NAME=${POSTGRES_NAME_TEST}" >> .env
          echo "POSTGRES_USERNAME=${POSTGRES_USERNAME_TEST}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}" >> .env
          cd ..

      - name: Run scripts test
        run: bash scripts/run_build_test.sh