name: Build Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # https://crontab.cronhub.io/
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Action for checking out a repo - https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # GitHub Action to set up Docker Buildx - https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        env:
          FLASK_SECRET_KEY_TEST: ${{ secrets.FLASK_SECRET_KEY_TEST }}
          BOT_TOKEN_TEST: ${{ secrets.BOT_TOKEN_TEST }}
          HASH_LOG_SALT_TEST: ${{ secrets.HASH_LOG_SALT_TEST }}
          POSTGRES_HOST_TEST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT_TEST: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_NAME_TEST: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USERNAME_TEST: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD_TEST: ${{ secrets.POSTGRES_PASSWORD }}
          PG_ADMIN_EMAIL: ${{ secrets.PG_ADMIN_EMAIL }}
          PG_ADMIN_PSW: ${{ secrets.PG_ADMIN_PSW }}
        run: |
          cd budget_graph
          echo "FLASK_SECRET_KEY=${FLASK_SECRET_KEY_TEST}" >> .env
          echo "BOT_TOKEN=${BOT_TOKEN_TEST}" >> .env
          echo "HASH_LOG_SALT"=${HASH_LOG_SALT_TEST} >> .env
          echo "POSTGRES_HOST=${POSTGRES_HOST}" >> .env
          echo "POSTGRES_PORT=${POSTGRES_PORT}" >> .env
          echo "POSTGRES_NAME=${POSTGRES_NAME}" >> .env
          echo "POSTGRES_USERNAME=${POSTGRES_USERNAME}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          cd ..
          cd db_auth
          echo "${PG_ADMIN_EMAIL}" >> pg_admin_email.env
          echo "${PG_ADMIN_PSW}" >> pg_admin_psw.env
          echo "${POSTGRES_PASSWORD_TEST}" >> psq_psw.env

      - name: Run scripts test
        run: bash scripts/run_build_test.sh