name: Eslint

on:
  push:
    paths-ignore:
      - 'tests/**'
  pull_request:
    paths-ignore:
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ESLint
        run: |
          npm install eslint --global

      - name: Lint with eslint
        run: |
          eslint . --ignore-pattern 'tests/**' # run ESLint, excluding the tests folder

