name: Golangci-lint

on:
  push:
    paths-ignore:
      - 'tests/**'
  pull_request:
    paths-ignore:
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Lint with golangci-lint
        run: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint run ./... --exclude-use-default # Запускаем линтер для всех файлов, исключая папку tests
