name: golangci-lint

on:
  push:
    paths-ignore:
      - 'tests/**'
  pull_request:
    paths-ignore:
      - 'tests/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Change directory to reCaptchaAPI
        run: cd reCaptchaAPI # Change the directory for working with the module

      - name: Initialize Go module
        run: go mod init budget_graph_recaptcha_api

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint with golangci-lint
        run: |
          golangci-lint run reCaptchaAPI/... --exclude-use-default # Run the linter for all files in the reCaptchaAPI dir
