name: UnitTests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # https://crontab.cronhub.io/
  push:
    branches: [ master, postgresql ]
  pull_request:

jobs:

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #  The job will be executed for every possible combination of variables.
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.12' ]

    steps:
      # Action for checking out a repo - https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          check-latest: true

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run UnitTests
        run: |
          cd tests || exit 1
          python -m pytest test_sources.py test_validators.py

  # database-queries-unit-tests:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ ubuntu-latest, macos-latest, windows-latest ]
  #       python-version: [ '3.11', '3.12' ]

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install PostgreSQL 16
  #       uses:

  #     - name: Setup python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         architecture: x64

  #     - name: Install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install pytest

  #     - name: Run UnitTests
  #       run: |
  #         cd tests || exit 1
  #         python manage_test_db.py
  #         python -m pytest test_database_queries.py